package:
  name: cairo
  version: 1.12.16

source:
  fn: cairo-1.12.16.tar.xz
  url: http://cairographics.org/releases/cairo-1.12.16.tar.xz

build:
  number: 0

requirements:
  build:
    - freetype
    - libpng
    - pixman
    - zlib
  run:
    - freetype
    - libpng
    - pixman
    - zlib

about:
  home: http://cairographics.org/
  license: LGPL 2.1 and MPL 1.1

# vim:set ts=8 sw=2 sts=2 tw=78 et:
