package:
  name: oracle11g-r2-client-win64
  version: 11.2.0.2.0

#source:
#  fn: ora_2.0-0.tar.gz
#  url: http://cran.r-project.org/src/contrib/ora_2.0-0.tar.gz

build:
  number: 0

#requirements:
#  build:
##    - r
#    - r-dbi
#    - r-roracle
#  run:
#    - r
#    - r-dbi
#    - r-roracle

about:
  license: OTN

# vim:set ts=8 sw=2 sts=2 tw=78 et:
